version: '3'

services:
  reverse-proxy:
    image: traefik:v1.7 # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    networks:
      - traefik
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker event
    
  whoami:
    networks:
      - traefik
    image: traefik/whoami # A container that exposes an API to show its IP address
    labels:
      - "traefik.frontend.rule=Host:whoami.docker.localhost"  
      
networks:
  traefik:
    external:
      name: traefik-reverse-proxy