version: '3.1'

services:
  wordpress:
    image: wordpress
    networks:
      - traefik
    labels:
      - "traefik.http.routers.wordpress.rule=Host(`wordpress.localhost`)"
      - "traefik.docker.network=traefik-reverse-proxy"
    # ports:
    #   - 9999:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_CONFIG_EXTRA:
        define( 'WP_DEBUG', false );
    volumes:
      - ./wp-content:/var/www/html/wp-content/

  db:
    image: mysql:8.0
    networks:
      - traefik
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql


  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    networks:
      - traefik
    labels:
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.localhost`)"
      - "traefik.docker.network=traefik-reverse-proxy"
    # ports:
    #   - '9998:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: example

volumes:
  wordpress:
  db:

networks:
  traefik:
    external:
      name: traefik-reverse-proxy